In [1]:
import numpy as np # by convention, "np" alias is used

### Arrays

#### Initialization

In [2]:
# array creation can be done with list initialization
a = np.array([1, 2, 3, 4, 5, 6]) # 1-d array (vector) 
print(a)
print(a.shape) # array dimensions

a2 = np.array([[1, 2, 2**2], [1, 3, 3**2], [1, 4, 4**2]]) # 2-d array (matrix) is initialized with list of lists
print(a2)

[1 2 3 4 5 6]
(6,)
[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [3]:
zeros_1d = np.zeros((6,)) # iniialize vector with zeroes
ones_1d = np.ones((6,)) # initialize vector with ones
print(zeros_1d)
print(ones_1d)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [4]:
zeros_2d = np.zeros((6,3)) # iniialize 2-d array with zeroes
ones_2d = np.ones((6,3)) # initialize 2-d array with ones
print(zeros_2d)
print(ones_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
np.arange(30) # integer range vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.linspace(0, 20, num=5) # linearly spaced vector

array([ 0.,  5., 10., 15., 20.])

In [7]:
print(np.random.rand(10) ) # (pseudo)random (uniformly distributed) number vector

print(np.random.rand(3, 3) ) # (pseudo)random (uniformly distributed) number 2d-array

[0.78173036 0.37717091 0.6211822  0.51138779 0.58512409 0.4170872
 0.46946354 0.02314114 0.70794652 0.87110705]
[[0.97684411 0.31371009 0.75738868]
 [0.64344279 0.39757735 0.45004398]
 [0.37014382 0.09052218 0.92571866]]


In [8]:
print(np.random.randn(6) ) # (pseudo)random (normally distributed) number vector

print(np.random.randn(2, 2) ) # (pseudo)random (normally distributed) number 2d-array

[-0.01010281 -1.20077807 -0.4702973   0.27223269  0.42161409  0.28567025]
[[ 0.50785083 -1.16982011]
 [-1.44057215 -1.23965709]]


#### Element-wise operations

In [9]:
# math operations work with arrays
print(a * 2) # scalar multiplication
print(a + 2) # scalar summation
print(a**2) # exponentiation

[ 2  4  6  8 10 12]
[3 4 5 6 7 8]
[ 1  4  9 16 25 36]


#### Pairwise operations

In [10]:
b = 2 + a
print("a = {}".format(a))
print("b = {}".format(b))
print("b + a = {}".format(b + a)) # vector pairwise summation
print("b - a = {}".format(b - a)) # vector pairwise subtraction
print("b * a = {}".format(b * a)) # vector pairwise multiplication

print("(a,b) = ", np.inner(b,a)) # inner product
print("(a,b) = ", sum(b*a)) # inner product (home edition)

a = [1 2 3 4 5 6]
b = [3 4 5 6 7 8]
b + a = [ 4  6  8 10 12 14]
b - a = [2 2 2 2 2 2]
b * a = [ 3  8 15 24 35 48]
(a,b) =  133
(a,b) =  133


#### Matrix operations

In [11]:
# original matrix (6 rows x 3 columns)
print(ones_2d)
print("original matrix dimensions = {}".format(ones_2d.shape) )

# transposed matrix (3 rows x 6 columns)
print(np.transpose(ones_2d))
print("original matrix dimensions = {}".format(np.transpose(ones_2d).shape) )

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
original matrix dimensions = (6, 3)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
original matrix dimensions = (3, 6)


In [12]:
vandermonde = np.array([[1, 2, 2**2], [1, 3, 3**2], [1, 4, 4**2]]) # Vandermonde matrix
print(vandermonde)

[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [13]:
vandermonde_inv = np.linalg.inv(vandermonde) # inverse Vandermonde matrix
print(vandermonde_inv)

[[ 6.  -8.   3. ]
 [-3.5  6.  -2.5]
 [ 0.5 -1.   0.5]]


In [14]:
print(np.matmul(vandermonde, vandermonde_inv)) # matrix multiplication

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.max(vandermonde))

16
