In [1]:
import numpy as np # by convention, "np" alias is used

### Arrays

#### Initialization

In [30]:
# array creation can be done with list initialization
a = np.array([1, 2, 3, 4, 5, 6]) # 1-d array (vector) 
print(a)
print(a.shape) # array dimensions

a2 = np.array([[1, 2, 2**2], [1, 3, 3**2], [1, 4, 4**2]]) # 2-d array is initialized with list of lists
print(a2)

[1 2 3 4 5 6]
(6,)
[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [31]:
zeros_1d = np.zeros((6,)) # iniialize vector with zeroes
ones_1d = np.ones((6,)) # initialize vector with ones
print(zeros_1d)
print(ones_1d)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [32]:
zeros_2d = np.zeros((6,3)) # iniialize 2-d array with zeroes
ones_2d = np.ones((6,3)) # initialize 2-d array with ones
print(zeros_2d)
print(ones_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
np.arange(30) # integer range vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
np.linspace(0, 20, num=5) # linearly spaced vector

array([ 0.,  5., 10., 15., 20.])

In [49]:
print(np.random.rand(10) ) # (pseudo)random (uniformly distributed) number vector

print(np.random.rand(3, 3) ) # (pseudo)random (uniformly distributed) number 2d-array

[0.50648289 0.18571168 0.15217123 0.63558561 0.88928209 0.21187429
 0.42554266 0.48929528 0.66153358 0.38749289]
[[0.07564385 0.25048015 0.47951731]
 [0.38365987 0.8767678  0.8885268 ]
 [0.40250816 0.42960846 0.50605994]]


In [47]:
print(np.random.randn(6) ) # (pseudo)random (normally distributed) number vector

print(np.random.randn(2, 2) ) # (pseudo)random (normally distributed) number 2d-array

[-0.8030791  -2.69349585  1.24204339 -0.85082059 -1.00291293  1.11442083]
[[ 0.82524885  0.15745778]
 [-0.1185536   0.59962207]]


#### Element-wise operations

In [15]:
# math operations work with arrays
print(a * 2) # scalar multiplication
print(a + 2) # scalar summation
print(a**2) # exponentiation

[ 2  4  6  8 10 12]
[3 4 5 6 7 8]
[ 1  4  9 16 25 36]


#### Pairwise operations

In [24]:
b = 2 + a
print("a = {}".format(a))
print("b = {}".format(b))
print("b + a = {}".format(b + a)) # vector pairwise summation
print("b - a = {}".format(b - a)) # vector pairwise subtraction
print("b * a = {}".format(b * a)) # vector pairwise multiplication

print("(a,b) = ", np.inner(b,a)) # inner product
print("(a,b) = ", sum(b*a)) # inner product (home edition)

a = [1 2 3 4 5 6]
b = [3 4 5 6 7 8]
b + a = [ 4  6  8 10 12 14]
b - a = [2 2 2 2 2 2]
b * a = [ 3  8 15 24 35 48]
(a,b) =  133
(a,b) =  133
